matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      language: cpp
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7.0
          packages:
            - clang-7.0
      language: cpp
      env:
        - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

    - os: osx
      osx_image: xcode10.1
      language: cpp

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd cmake && make